"""Regenerate src/functions.rs from the Trino documentation.

The function catalog ships in the repo at src/functions.rs so that builds are
offline and deterministic; this script only needs to run when Trino's docs
change (a release-scale event).

Usage::

    python tools/extract_functions.py [--docs-path PATH]

Fetch mode (default): downloads the current ``functions/*.md`` + ``list.md``
from raw.githubusercontent.com/trinodb/trino/master. Pass ``--docs-path`` to
point at a local checkout of ``trinodb/trino/docs/src/main/sphinx/functions``.

Requires only the Python standard library.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

FUNCTIONS_PATH = "docs/src/main/sphinx/functions"
RAW_BASE = "https://raw.githubusercontent.com/trinodb/trino/master/"

# Directory listing of functions/ on the remote branch.
FUNCTION_FILES = [
    "aggregate.md",
    "ai.md",
    "array.md",
    "binary.md",
    "bitwise.md",
    "color.md",
    "comparison.md",
    "conditional.md",
    "conversion.md",
    "datasketches.md",
    "datetime.md",
    "decimal.md",
    "geospatial.md",
    "hyperloglog.md",
    "ipaddress.md",
    "json.md",
    "lambda.md",
    "list-by-topic.md",
    "list.md",
    "logical.md",
    "map.md",
    "math.md",
    "ml.md",
    "qdigest.md",
    "regexp.md",
    "row.md",
    "session.md",
    "setdigest.md",
    "string.md",
    "system.md",
    "table.md",
    "tdigest.md",
    "teradata.md",
    "url.md",
    "uuid.md",
    "variant.md",
    "window.md",
]

DIRECTIVE_RE = re.compile(r":::\{function\}\s+([a-zA-Z0-9_]+)")
CROSS_REF_RE = re.compile(r"\{func\}\s*`([a-zA-Z0-9_]+)`")

OUT_PATH = Path(__file__).resolve().parent.parent / "src" / "functions.rs"


def fetch(name: str) -> str | None:
    url = f"{RAW_BASE}{FUNCTIONS_PATH}/{name}"
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.HTTPError:
        return None


def read_local(directory: Path, name: str) -> str | None:
    path = directory / name
    return path.read_text(encoding="utf-8") if path.is_file() else None


def extract_names(docs: dict[str, str]) -> set[str]:
    names: set[str] = set()
    for content in docs.values():
        names.update(DIRECTIVE_RE.findall(content))
        names.update(CROSS_REF_RE.findall(content))
    return {name.lower() for name in names}


def render_rust(names: set[str]) -> str:
    ordered = sorted(names)
    lines = [
        r"// @generated by tools/extract_functions.py — DO NOT EDIT BY HAND.",
        r"//",
        r"// Canonical Trino function names, extracted from the Trino docs",
        r"// (docs/src/main/sphinx/functions/*.md), union of `::{function}`",
        r"// directives and `{func}` cross-references. Regenerate when Trino",
        r"// docs change: python tools/extract_functions.py",
        r"//",
        r"use std::sync::LazyLock;",
        r"",
        r"static FUNCTIONS: LazyLock<std::collections::HashSet<&'static str>> =",
        r"    LazyLock::new(|| {",
        r"        let mut set = std::collections::HashSet::new();",
        r"        for name in [",
    ]
    for name in ordered:
        lines.append(f'            "{name}",')
    lines += [
        r"        ] {",
        r"            set.insert(name);",
        r"        }",
        r"        set",
        r"    });",
        r"",
        r"pub fn is_known_function(name: &str) -> bool {",
        r"    FUNCTIONS.contains(name)",
        r"}",
        r"",
        r"#[cfg(test)]",
        r"mod tests {",
        r"    use super::*;",
        r"",
        r"    #[test]",
        r"    fn catalog_has_core_functions() {",
        r'        for name in ["count", "sum", "avg", "min", "max", "coalesce", "try", "if"] {',
        r"            assert!(",
        r"                is_known_function(name),",
        r'                "expected {name} to be in the Trino function catalog",',
        r"            );",
        r"        }",
        r"    }",
        r"",
        r"    #[test]",
        r"    fn known_and_unknown_names() {",
        r'        assert!(is_known_function("round"));',
        r'        assert!(is_known_function("array_agg"));',
        r'        assert!(!is_known_function("marh"));',
        r'        assert!(!is_known_function("roundd"));',
        r"    }",
        r"}",
        r"",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-path",
        default=None,
        help="local checkout of trinodb/trino/docs/src/main/sphinx/functions",
    )
    args = parser.parse_args()

    if args.docs_path:
        directory = Path(args.docs_path)
        docs = {
            name: read_local(directory, name)
            for name in FUNCTION_FILES
            if (directory / name).is_file()
        }
        missing = [n for n in FUNCTION_FILES if n not in docs]
        if missing:
            print(
                f"warning: missing files in {directory}: {', '.join(missing)}",
                file=sys.stderr,
            )
    else:
        docs = {}
        for name in FUNCTION_FILES:
            content = fetch(name)
            if content is not None:
                docs[name] = content

    if not docs:
        print("error: no documentation files loaded", file=sys.stderr)
        sys.exit(1)

    names = extract_names(docs)
    print(f"extracted {len(names)} unique function names from {len(docs)} files")

    OUT_PATH.write_text(render_rust(names), encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()