"""Regenerate src/types.rs from the Trino data-type documentation.

The built-in type catalog ships in the repo at src/types.rs so that builds are
offline and deterministic; this script only needs to run when Trino's docs
change (a release-scale event).

Usage::

    python tools/extract_types.py [--docs-path PATH]

Fetch mode (default): downloads ``docs/src/main/sphinx/language/types.md`` from
raw.githubusercontent.com/trinodb/trino/master. Pass ``--docs-path`` to point
at a local checkout of ``trinodb/trino``.

Type names are taken from ``### `TYPE`` headings; the first word of each name is
also registered (so ``TIME(P)`` and ``TIME WITH TIME ZONE`` both cover the
``time`` base name). Alias ``INT`` is a standalone heading and needs no special
handling.

Requires only the Python standard library.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

DOC_PATH = "docs/src/main/sphinx/language/types.md"
RAW_BASE = "https://raw.githubusercontent.com/trinodb/trino/master/"

# A `###` heading may carry one or more backticked type names, e.g.
# `### `INTEGER` or `INT``.
HEADING_RE = re.compile(r"`([^`]+)`")

OUT_PATH = Path(__file__).resolve().parent.parent / "src" / "types.rs"


def extract_names(content: str) -> set[str]:
    names: set[str] = set()
    for line in content.splitlines():
        if not line.startswith("###"):
            continue
        for match in HEADING_RE.finditer(line):
            name = match.group(1)
            names.add(name.lower())
            # `TIME(P)`, `TIME WITH TIME ZONE`, `INTERVAL YEAR TO MONTH`, ...
            first = re.sub(r"\(.*", "", name.split()[0].lower())
            names.add(first)
    return names


def render_rust(names: set[str]) -> str:
    ordered = sorted(names)
    lines = [
        r"// @generated by tools/extract_types.py — DO NOT EDIT BY HAND.",
        r"//",
        r"// Canonical Trino data-type names, extracted from the Trino docs",
        r"// (docs/src/main/sphinx/language/types.md): the `### TYPE` headings,",
        r"// plus the first word of parametrized/phrased headings (so `TIME(P)`",
        r"// and `TIME WITH TIME ZONE` both register the `time` base name).",
        r"// Regenerate when Trino docs change: python tools/extract_types.py",
        r"//",
        r"use std::sync::LazyLock;",
        r"",
        r"static TYPES: LazyLock<std::collections::HashSet<&'static str>> =",
        r"    LazyLock::new(|| {",
        r"        let mut set = std::collections::HashSet::new();",
        r"        for name in [",
    ]
    for name in ordered:
        lines.append(f'            "{name}",')
    lines += [
        r"        ] {",
        r"            set.insert(name);",
        r"        }",
        r"        set",
        r"    });",
        r"",
        r"pub fn is_known_type(name: &str) -> bool {",
        r"    TYPES.contains(name)",
        r"}",
        r"",
        r"#[cfg(test)]",
        r"mod tests {",
        r"    use super::*;",
        r"",
        r"    #[test]",
        r"    fn catalog_has_core_types() {",
        r'        for name in ["bigint", "varchar", "date", "decimal", "row", "map", "array"] {',
        r"            assert!(",
        r"                is_known_type(name),",
        r'                "expected {name} to be in the Trino type catalog",',
        r"            );",
        r"        }",
        r"    }",
        r"",
        r"    #[test]",
        r"    fn known_and_unknown_names() {",
        r'        assert!(is_known_type("varchar"));',
        r'        assert!(is_known_type("int"));',
        r'        assert!(is_known_type("timestamp"));',
        r'        assert!(!is_known_type("bignum"));',
        r"    }",
        r"}",
        r"",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-path",
        default=None,
        help="local checkout of trinodb/trino",
    )
    args = parser.parse_args()

    if args.docs_path:
        directory = Path(args.docs_path)
        path = directory / DOC_PATH
        if not path.is_file():
            print(f"error: {path} not found", file=sys.stderr)
            sys.exit(1)
        content = path.read_text(encoding="utf-8")
    else:
        url = f"{RAW_BASE}{DOC_PATH}"
        try:
            with urllib.request.urlopen(url, timeout=30) as resp:
                content = resp.read().decode("utf-8")
        except urllib.error.HTTPError as err:
            print(f"error: failed to fetch {url}: {err}", file=sys.stderr)
            sys.exit(1)

    names = extract_names(content)
    print(f"extracted {len(names)} unique type names")

    OUT_PATH.write_text(render_rust(names), encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()