"""Regenerate the committed Trino function catalog from pinned documentation."""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
from pathlib import Path

try:
    from .catalog_common import (
        check_outputs,
        read_local_files,
        read_remote_files,
        render_manifest,
        write_outputs,
    )
except ImportError:
    from catalog_common import (
        check_outputs,
        read_local_files,
        read_remote_files,
        render_manifest,
        write_outputs,
    )

DEFAULT_REF = "483"
FUNCTIONS_PATH = "docs/src/main/sphinx/functions"
FUNCTION_FILES = [
    "aggregate.md",
    "ai.md",
    "array.md",
    "binary.md",
    "bitwise.md",
    "color.md",
    "comparison.md",
    "conditional.md",
    "conversion.md",
    "datasketches.md",
    "datetime.md",
    "decimal.md",
    "geospatial.md",
    "hyperloglog.md",
    "ipaddress.md",
    "json.md",
    "lambda.md",
    "list-by-topic.md",
    "list.md",
    "logical.md",
    "map.md",
    "math.md",
    "ml.md",
    "qdigest.md",
    "regexp.md",
    "row.md",
    "session.md",
    "setdigest.md",
    "string.md",
    "system.md",
    "table.md",
    "tdigest.md",
    "teradata.md",
    "url.md",
    "uuid.md",
    "variant.md",
    "window.md",
]
DOC_PATHS = [f"{FUNCTIONS_PATH}/{name}" for name in FUNCTION_FILES]
DIRECTIVE_RE = re.compile(r":::\{function\}\s+([a-zA-Z0-9_]+)")
CROSS_REF_RE = re.compile(r"\{func\}\s*`([a-zA-Z0-9_]+)`")
SPECIAL_FUNCTIONS = {
    "current_date",
    "current_time",
    "current_timestamp",
    "grouping",
    "json_array",
    "json_exists",
    "json_object",
    "json_query",
    "json_value",
    "localtime",
    "localtimestamp",
}
ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "src" / "functions.rs"
MANIFEST_PATH = ROOT / "src" / "functions.manifest.json"


def extract_names(docs: dict[str, str]) -> set[str]:
    names: set[str] = set()
    for content in docs.values():
        names.update(DIRECTIVE_RE.findall(content))
        names.update(CROSS_REF_RE.findall(content))
    extracted = {name.lower() for name in names}
    if not extracted:
        raise ValueError("no documented function declarations found")
    return extracted | SPECIAL_FUNCTIONS


def render_rust(names: set[str]) -> str:
    lines = [
        "// @generated by tools/extract_functions.py — DO NOT EDIT BY HAND.",
        "// Source revision and file checksums: src/functions.manifest.json.",
        "//",
        "use std::sync::LazyLock;",
        "",
        "static FUNCTIONS: LazyLock<std::collections::HashSet<&'static str>> = LazyLock::new(|| {",
        "    let mut set = std::collections::HashSet::new();",
        "    for name in [",
    ]
    lines.extend(f'        "{name}",' for name in sorted(names))
    lines += [
        "    ] {",
        "        set.insert(name);",
        "    }",
        "    set",
        "});",
        "",
        "pub fn is_known_function(name: &str) -> bool {",
        "    FUNCTIONS.contains(name)",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn catalog_has_core_functions() {",
        '        for name in ["count", "sum", "avg", "min", "max", "coalesce", "try", "if"] {',
        "            assert!(",
        "                is_known_function(name),",
        '                "expected {name} to be in the Trino function catalog",',
        "            );",
        "        }",
        "    }",
        "",
        "    #[test]",
        "    fn known_and_unknown_names() {",
        '        assert!(is_known_function("round"));',
        '        assert!(is_known_function("array_agg"));',
        '        assert!(!is_known_function("marh"));',
        '        assert!(!is_known_function("roundd"));',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-path", type=Path, help="local trinodb/trino checkout")
    parser.add_argument("--ref", default=DEFAULT_REF, help="Trino git ref for remote mode")
    parser.add_argument("--check", action="store_true", help="fail if committed output differs")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        if args.docs_path:
            root = args.docs_path
            if (root / FUNCTION_FILES[0]).is_file():
                root = root.parents[4]
            docs, manifest = read_local_files(root, DOC_PATHS)
        else:
            docs, manifest = read_remote_files(args.ref, DOC_PATHS)
        names = extract_names(docs)
    except (OSError, ValueError, urllib.error.URLError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1) from error

    manifest["generator"] = "tools/extract_functions.py"
    manifest["entry_count"] = len(names)
    outputs = {
        OUT_PATH: render_rust(names),
        MANIFEST_PATH: render_manifest(manifest),
    }
    if args.check:
        if not check_outputs(outputs):
            print("error: committed function catalog is out of date", file=sys.stderr)
            raise SystemExit(1)
        print(f"function catalog is current ({len(names)} names)")
        return
    write_outputs(outputs)
    print(f"wrote {OUT_PATH} and {MANIFEST_PATH} ({len(names)} names)")


if __name__ == "__main__":
    main()
