"""Regenerate the committed Trino type catalog from pinned documentation."""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
from pathlib import Path

try:
    from .catalog_common import (
        check_outputs,
        read_local_files,
        read_remote_files,
        render_manifest,
        write_outputs,
    )
except ImportError:
    from catalog_common import (
        check_outputs,
        read_local_files,
        read_remote_files,
        render_manifest,
        write_outputs,
    )

DEFAULT_REF = "483"
TYPE_DOC = "docs/src/main/sphinx/language/types.md"
GEOSPATIAL_DOC = "docs/src/main/sphinx/functions/geospatial.md"
DOC_PATHS = [TYPE_DOC, GEOSPATIAL_DOC]
HEADING_RE = re.compile(r"`([^`]+)`")
DOCUMENTED_TYPES = {
    GEOSPATIAL_DOC: {"bingtile", "geometry", "sphericalgeography"},
}
ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "src" / "types.rs"
MANIFEST_PATH = ROOT / "src" / "types.manifest.json"


def extract_names(docs: dict[str, str]) -> set[str]:
    content = docs[TYPE_DOC]
    names: set[str] = set()
    for line in content.splitlines():
        if not line.startswith("###"):
            continue
        for match in HEADING_RE.finditer(line):
            name = match.group(1)
            names.add(name.lower())
            names.add(re.sub(r"\(.*", "", name.split()[0].lower()))
    if not names:
        raise ValueError(f"no type headings found in {TYPE_DOC}")
    for path, documented in DOCUMENTED_TYPES.items():
        lower = docs[path].lower()
        missing = sorted(name for name in documented if name not in lower)
        if missing:
            raise ValueError(f"documented types missing from {path}: {', '.join(missing)}")
        names.update(documented)
    return names


def render_rust(names: set[str]) -> str:
    lines = [
        "// @generated by tools/extract_types.py — DO NOT EDIT BY HAND.",
        "// Source revision and file checksums: src/types.manifest.json.",
        "//",
        "use std::sync::LazyLock;",
        "",
        "static TYPES: LazyLock<std::collections::HashSet<&'static str>> = LazyLock::new(|| {",
        "    let mut set = std::collections::HashSet::new();",
        "    for name in [",
    ]
    lines.extend(f'        "{name}",' for name in sorted(names))
    lines += [
        "    ] {",
        "        set.insert(name);",
        "    }",
        "    set",
        "});",
        "",
        "pub fn is_known_type(name: &str) -> bool {",
        "    TYPES.contains(name)",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn catalog_has_core_types() {",
        "        for name in [",
        '            "bigint", "varchar", "date", "decimal", "row", "map", "array",',
        "        ] {",
        "            assert!(",
        "                is_known_type(name),",
        '                "expected {name} to be in the Trino type catalog",',
        "            );",
        "        }",
        "    }",
        "",
        "    #[test]",
        "    fn catalog_has_documented_geospatial_types() {",
        '        for name in ["geometry", "sphericalgeography", "bingtile"] {',
        "            assert!(is_known_type(name));",
        "        }",
        "    }",
        "",
        "    #[test]",
        "    fn known_and_unknown_names() {",
        '        assert!(is_known_type("varchar"));',
        '        assert!(is_known_type("int"));',
        '        assert!(is_known_type("timestamp"));',
        '        assert!(!is_known_type("bignum"));',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-path", type=Path, help="local trinodb/trino checkout")
    parser.add_argument("--ref", default=DEFAULT_REF, help="Trino git ref for remote mode")
    parser.add_argument("--check", action="store_true", help="fail if committed output differs")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        if args.docs_path:
            docs, manifest = read_local_files(args.docs_path, DOC_PATHS)
        else:
            docs, manifest = read_remote_files(args.ref, DOC_PATHS)
        names = extract_names(docs)
    except (OSError, ValueError, urllib.error.URLError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1) from error

    manifest["generator"] = "tools/extract_types.py"
    manifest["entry_count"] = len(names)
    outputs = {
        OUT_PATH: render_rust(names),
        MANIFEST_PATH: render_manifest(manifest),
    }
    if args.check:
        if not check_outputs(outputs):
            print("error: committed type catalog is out of date", file=sys.stderr)
            raise SystemExit(1)
        print(f"type catalog is current ({len(names)} names)")
        return
    write_outputs(outputs)
    print(f"wrote {OUT_PATH} and {MANIFEST_PATH} ({len(names)} names)")


if __name__ == "__main__":
    main()
