// @generated by tools/extract_types.py — DO NOT EDIT BY HAND.
//
// Canonical Trino data-type names, extracted from the Trino docs
// (docs/src/main/sphinx/language/types.md): the `### TYPE` headings,
// plus the first word of parametrized/phrased headings (so `TIME(P)`
// and `TIME WITH TIME ZONE` both register the `time` base name).
// Regenerate when Trino docs change: python tools/extract_types.py
//
use std::sync::LazyLock;

static TYPES: LazyLock<std::collections::HashSet<&'static str>> = LazyLock::new(|| {
    let mut set = std::collections::HashSet::new();
    for name in [
        "array",
        "bigint",
        "boolean",
        "char",
        "date",
        "decimal",
        "double",
        "hyperloglog",
        "int",
        "integer",
        "interval",
        "interval day to second",
        "interval year to month",
        "ipaddress",
        "json",
        "map",
        "number",
        "p4hyperloglog",
        "qdigest",
        "real",
        "row",
        "setdigest",
        "smallint",
        "tdigest",
        "time",
        "time with time zone",
        "time(p)",
        "timestamp",
        "timestamp with time zone",
        "timestamp(p)",
        "timestamp(p) with time zone",
        "tinyint",
        "uuid",
        "varbinary",
        "varchar",
        "variant",
    ] {
        set.insert(name);
    }
    set
});

pub fn is_known_type(name: &str) -> bool {
    TYPES.contains(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_core_types() {
        for name in [
            "bigint", "varchar", "date", "decimal", "row", "map", "array",
        ] {
            assert!(
                is_known_type(name),
                "expected {name} to be in the Trino type catalog",
            );
        }
    }

    #[test]
    fn known_and_unknown_names() {
        assert!(is_known_type("varchar"));
        assert!(is_known_type("int"));
        assert!(is_known_type("timestamp"));
        assert!(!is_known_type("bignum"));
    }
}
