// @generated by tools/extract_types.py — DO NOT EDIT BY HAND.
// Source revision and file checksums: src/types.manifest.json.
//
use std::sync::LazyLock;

static TYPES: LazyLock<std::collections::HashSet<&'static str>> = LazyLock::new(|| {
    let mut set = std::collections::HashSet::new();
    for name in [
        "array",
        "bigint",
        "bingtile",
        "boolean",
        "char",
        "date",
        "decimal",
        "double",
        "geometry",
        "hyperloglog",
        "int",
        "integer",
        "interval",
        "interval day to second",
        "interval year to month",
        "ipaddress",
        "json",
        "map",
        "number",
        "p4hyperloglog",
        "qdigest",
        "real",
        "row",
        "setdigest",
        "smallint",
        "sphericalgeography",
        "tdigest",
        "time",
        "time with time zone",
        "time(p)",
        "timestamp",
        "timestamp with time zone",
        "timestamp(p)",
        "timestamp(p) with time zone",
        "tinyint",
        "uuid",
        "varbinary",
        "varchar",
        "variant",
    ] {
        set.insert(name);
    }
    set
});

pub fn is_known_type(name: &str) -> bool {
    TYPES.contains(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_core_types() {
        for name in [
            "bigint", "varchar", "date", "decimal", "row", "map", "array",
        ] {
            assert!(
                is_known_type(name),
                "expected {name} to be in the Trino type catalog",
            );
        }
    }

    #[test]
    fn catalog_has_documented_geospatial_types() {
        for name in ["geometry", "sphericalgeography", "bingtile"] {
            assert!(is_known_type(name));
        }
    }

    #[test]
    fn known_and_unknown_names() {
        assert!(is_known_type("varchar"));
        assert!(is_known_type("int"));
        assert!(is_known_type("timestamp"));
        assert!(!is_known_type("bignum"));
    }
}
